name: Test Python Scripts with Conda YAML

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: build/conda/environment.yml  # Replace with your env file name
          auto-activate-base: true

      - name: Run tests
        env:
          CONDA_ACTIVATE: ${{ steps.conda_env.outputs.activate }}
        run: |
          python -m pytest


